import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ThemeProvider } from "../lib/ThemeContext";
import AnimatedGridPattern from "../@/components/ui/animatedGrid";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      
    <ThemeProvider>
      
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </html>

        </ThemeProvider>
       
        </ClerkProvider>

  );
}
